# Generated by Django 4.2.5 on 2023-09-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("herald", "0005_auto_20180516_1755"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="sentnotification",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
