language: python

sudo: false

cache: pip

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - DJANGO='https://github.com/django/django/archive/master.tar.gz'
  - DJANGO='django>=2.0,<2.1.0'
  - DJANGO='django>=1.11.0,<1.12.0'

install:
  - travis_retry pip install --upgrade pip setuptools wheel
  - travis_retry pip install --upgrade $DJANGO
  - travis_retry pip install --upgrade -r requirements.txt

script:
  - coverage run --source herald runtests.py -v 2

notifications:
  email: false

matrix:
  exclude:
    - python: "2.7"
      env: DJANGO='https://github.com/django/django/archive/master.tar.gz'
    - python: "2.7"
      env: DJANGO='django>=2.0,<2.1.0'
    - python: "3.4"
      env: DJANGO='https://github.com/django/django/archive/master.tar.gz'

  allow_failures:
    - env: DJANGO='https://github.com/django/django/archive/master.tar.gz'
  fast_finish: true

after_success:
    - coveralls